Add `py-ittapi`
If you see the following error, it is because the required python
version is not found when installing the wheel.

```
ERROR: ittapi-1.2.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/cli/req_command.py", line 68, in wrapper
    return func(self, options, args)
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/commands/install.py", line 387, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 77, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 545, in collect_root_requirements
    reqs = list(
        self._make_requirements_from_install_req(
    ...<2 lines>...
        )
    )
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 496, in _make_requirements_from_install_req
    self._fail_if_link_is_unsupported_wheel(ireq.link)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/thilina/share/spack/opt/spack/linux-zen3/py-pip-25.1.1-um6eltop5vx7p2pwmxnkhirddm4h2poq/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 147, in _fail_if_link_is_unsupported_wheel
    raise UnsupportedWheel(msg)
pip._internal.exceptions.UnsupportedWheel: ittapi-1.2.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```